#!/bin/sh

var_eula_file=$DIR_SERVER/eula.txt

get_eula_file_value() {
    if grep -q "eula=true" $var_eula_file; then
        echo "true"
    else
        echo "false"
    fi
}

get_eula_file_exists() {
    if [ ! -f $var_eula_file ]; then # Check that eula.txt exists
        echo "false"
    elif ! grep -q "eula=" $var_eula_file; then # Check that eula.txt contains eula= variable (i.e check it isn't empty)
        rm $var_eula_file
        echo "false"
    else
        echo "true"
    fi
}

sign_eula_file() {
    var_eula_file_value=$(get_eula_file_value)
    sed "s/$var_eula_file_value/$1/" "$var_eula_file" > "$var_eula_file.tmp"
    mv "$var_eula_file.tmp" "$var_eula_file"
    export EULA=$1
    echo "EULA has been updated!:"
    cat "$var_eula_file"
}

# Check if correct arguments are given
if [ $# -gt 1 ]; then
    echo "Usage: $0 [true|false]"
    exit 1
fi

if [ "$(get_eula_file_exists)" = "false" ]; then
    echo "eula.txt does not exist! Please run Spigot server once to generate the file."
    exit
fi

# Check if eula.txt is already signed
if [ "$(get_eula_file_value)" = "true" ]; then
    echo "eula.txt is signed."
    exit
else
    echo "eula.txt is currently unsigned."
fi

# Sign EULA if argument is given
if [ $# -eq 1 ]; then
    sign_eula_file "$1"
    echo "eula.txt has been signed with $1"
fi